#!/usr/bin/env sh

: ${DIRECTORY}
: ${IP}
: ${PORT}

s6-sleep 1

ENDPOINT="$(
    HOME=/root \
    /usr/local/bin/mega-exec webdav --port="$PORT" --public "$DIRECTORY" \
    | awk '{print $NF}' \
    | sed "s|127.0.0.1|${IP}|"
)"
