#!/usr/bin/env sh

: ${MEGA_DIRECTORY}

sleep 1

ENDPOINT="$(
    HOME=/root \
    /usr/local/bin/mega-exec webdav --port="10000" --public "$MEGA_DIRECTORY" \
    | awk '{print $NF}'
)"

sed -E \
    -e "s|(mega_endpoint = )\"\"|\1\"${ENDPOINT}\"|" \
    -i /opt/mitmdump/rewrite-paths.py
