#!/usr/bin/env sh

: ${MEGA_IP}
: ${MEGA_PORT}

. /opt/mitmdump/venv/bin/activate

setsid /opt/mitmdump/index.py \
    --set "flow_detail=1" \
    --set "termlog_verbosity=error" \
    --set "listen_host=0.0.0.0" \
    --set "listen_port=80" \
    --mode "reverse:http://${MEGA_IP}:${MEGA_PORT}" \
    --set "keep_host_header=true" \
    --set "stream_large_bodies=32m" \
    -s "/opt/mitmdump/fix-directory-move.py" \
    -s "/opt/mitmdump/fix-directory-timestamps.py"
