#!/usr/bin/env sh

: ${WEBDAV_PASSWORD_HASH}
: ${WEBDAV_USERNAME}

sed -E \
    -e "s|^(password_hash = )|\1\"${WEBDAV_PASSWORD_HASH}\"|" \
    -e "s|^(username = )|\1\"${WEBDAV_USERNAME}\"|" \
    -i "/opt/mitmdump/check-authentication.py"

. /opt/mitmdump/venv/bin/activate

exec /opt/mitmdump/index.py \
    --mode "reverse:http://127.0.0.1:10000" \
    --set "flow_detail=1" \
    --set "termlog_verbosity=error" \
    --set "listen_host=0.0.0.0" \
    --set "listen_port=80" \
    --set "keep_host_header=false" \
    -s "/opt/mitmdump/check-authentication.py" \
    -s "/opt/mitmdump/fix-directory-move.py" \
    -s "/opt/mitmdump/fix-directory-timestamps.py" \
    -s "/opt/mitmdump/rewrite-paths.py" \
    -s "/opt/mitmdump/skip-apple-files.py" \
    -s "/opt/mitmdump/stream-files.py"
